### PR TITLE
Add videos

### PR DESCRIPTION
**Pull request by jamesatjaminit**
Added videos to the assembly guide

### CODE REVIEW

**Comment by thinkingsand** [comment]
I feel like the soldering the LEDs video should be on step 5 too. Also we need a space before them all just add a <p> before the embed text

**Comment by jamesatjaminit** [comment]
Noted, I've added those now

**Comment by thinkingsand** [comment]
All good. Merged.

**Comment by thinkingsand** [comment]
Please lock the repo now

**Pull request merged**
